import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, section?: string) => string;
}

const translations: Record<Language, Record<string, Record<string, string>>> = {
  tr: {
    common: {
      uploadImage: 'Görsel Yükle',
      gallery: 'Galerim',
      premium: 'Premium Satın Al',
      admin: 'Yönetim',
      login: 'Giriş Yap',
      register: 'Kayıt Ol',
      logout: 'Çıkış Yap',
      about: 'Hakkımızda',
      terms: 'Kullanım Koşulları',
      help: 'Sıkça Sorulan Sorular',
      support: 'Destek Talebi',
      report: 'Resim İhbar',
      loading: 'Yükleniyor, lütfen bekleyin...',
      copied: 'Kopyalandı!',
      copy: 'Kopyala',
      delete: 'Sil',
      download: 'İndir',
      cancel: 'İptal',
      save: 'Kaydet',
      close: 'Kapat',
      all: 'Hepsi',
      status: 'Sistem Durumu',
      active: 'Aktif',
      cloud: 'Bulut',
      local: 'Yerel',
      maintenance: 'Sistem Bakımdadır',
      maintenance_desc: 'Sizlere daha hızlı ve kararlı bir hizmet sunabilmek için şu anda planlı bakım çalışması gerçekleştirmekteyiz. Çok yakında tekrar aktif olacağız!',
      admin_login: 'Yönetici Girişi',
      announcements: 'Yönetici Duyuruları',
      back: 'Geri Dön',
      required: 'Zorunlu alan',
      success: 'Başarılı',
      error: 'Hata',
      warning: 'Uyarı',
      fast_secure: 'Hızlı & Güvenli',
    },
    navbar: {
      more: 'Bilgi ve Yardım',
      corporate: 'Kurumsal & Bilgi',
      guest: 'Misafir',
      welcome: 'Hoş geldin,',
      settings: 'Profil & Ayarlar',
      admin_panel: 'Admin Paneli',
      support_messages: 'Destek Taleplerim',
      theme_settings: 'Arayüz Teması',
      theme_midnight: 'Gece Mavisi (Derin Siyah)',
      theme_slate: 'Kömür Grisi (Slate)',
    },
    uploader: {
      title: 'Hızlı ve Güvenli Resim Yükleme',
      subtitle: 'Görsellerinizi anında yükleyin, optimize edilmiş linklerle paylaşın.',
      drag_drop: 'Görsellerinizi buraya sürükleyin veya',
      browse: 'Dosya Seçin',
      allowed_formats: 'PNG, JPG, JPEG, WEBP, GIF (Maks. {size}MB)',
      uploading: 'Görseller Yükleniyor...',
      success: 'Yükleme Başarılı!',
      guest_limit: 'Misafir olarak {limit} yükleme hakkınız kaldı. Sınırsız saklama ve gelişmiş özellikler için üye olun!',
      guest_exhausted: 'Misafir yükleme limitiniz doldu! Görsel yüklemeye devam etmek için ücretsiz hesap oluşturun.',
      terms_warning: 'Görsel yükleyerek kullanım koşullarımızı kabul etmiş sayılırsınız.',
      private_mode: 'Gizli Görsel (Sadece ben görebileyim)',
      auto_delete: 'Otomatik Silinme Süresi',
      no_delete: 'Asla Silinmesin',
      delete_1h: '1 Saat Sonra Silinsin',
      delete_1d: '1 Gün Sonra Silinsin',
      delete_7d: '7 Gün Sonra Silinsin',
      delete_30d: '30 Gün Sonra Silinsin',
      upload_btn: 'Seçilenleri Yükle',
      clear_btn: 'Temizle',
      upload_more: 'Daha Fazla Yükle',
      viewer_link: 'İzleme Sayfası Linki',
      direct_link: 'Doğrudan Resim Linki',
      html_link: 'HTML Resim Kodu',
      bbcode_link: 'BBCode Resim Kodu',
      select_all: 'Hepsini Seç',
      editor: 'Editör',
      edit_image: 'Resmi Düzenle',
    },
    gallery: {
      title: 'Kişisel Galerim',
      subtitle: 'Yüklediğiniz tüm görselleri tek bir yerden yönetin.',
      empty: 'Henüz hiç görsel yüklememişsiniz.',
      empty_desc: 'Hemen ana sayfaya dönüp ilk görselinizi yükleyebilirsiniz!',
      delete_confirm: 'Bu görseli silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
      private: 'Gizli',
      public: 'Açık',
      views: 'görüntülenme',
      total_images: 'Toplam Görsel',
      total_views: 'Toplam Görüntülenme',
    },
    image_detail: {
      title: 'Görsel Detayları',
      uploaded_by: 'Yükleyen',
      uploaded_at: 'Yüklenme Tarihi',
      views: 'Görüntülenme Sayısı',
      dimensions: 'Çözünürlük',
      file_size: 'Dosya Boyutu',
      file_format: 'Format',
      expires_at: 'Silinme Tarihi',
      links: 'Paylaşım Linkleri',
      download: 'Görseli İndir',
      report: 'Görseli Bildir',
      delete: 'Görseli Sil',
      delete_confirm: 'Bu görsel kalıcı olarak silinecektir. Emin misiniz?',
      reported_success: 'Görsel başarıyla ihbar edildi. Teşekkürler.',
      copied_msg: 'Link başarıyla kopyalandı!',
    },
    premium: {
      title: 'Premium Paket',
      subtitle: 'Sınırsız hız, sıfır reklam ve ekstra özelliklerle deneyiminizi zirveye taşıyın.',
      features_title: 'Neden Premium?',
      feat_ads: 'Tamamen Reklamsız Deneyim',
      feat_ads_desc: 'Sitenin hiçbir yerinde reklam görmezsiniz.',
      feat_limit: '25 Adete Kadar Toplu Yükleme',
      feat_limit_desc: 'Tek seferde 25 adete kadar görseli eşzamanlı yükleyin.',
      feat_speed: 'Sınırsız Yükleme & İndirme Hızı',
      feat_speed_desc: 'Bant genişliği kısıtlaması olmadan maksimum hız.',
      feat_expiry: 'Asla Silinmeyen Görseller',
      feat_expiry_desc: 'Premium görselleri siz silene kadar ömür boyu saklanır.',
      feat_editor: 'Gelişmiş Görsel Editörü',
      feat_editor_desc: 'Görsellerinizi kırpın, filtreler uygulayın ve düzenleyin.',
      feat_support: '7/24 Öncelikli Canlı Destek',
      feat_support_desc: 'Talepleriniz en geç 1 saat içinde yanıtlanır.',
      monthly: 'Aylık Plan',
      yearly: 'Yıllık Plan',
      purchase: 'Premium Satın Al',
      active_premium: 'Premium Üyeliğiniz Aktif',
      expires_at: 'Bitiş Tarihi: {date}',
    }
  },
  en: {
    common: {
      uploadImage: 'Upload Image',
      gallery: 'My Gallery',
      premium: 'Buy Premium',
      admin: 'Admin',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      about: 'About Us',
      terms: 'Terms of Use',
      help: 'FAQ',
      support: 'Support',
      report: 'Report Abuse',
      loading: 'Loading, please wait...',
      copied: 'Copied!',
      copy: 'Copy',
      delete: 'Delete',
      download: 'Download',
      cancel: 'Cancel',
      save: 'Save',
      close: 'Close',
      all: 'All',
      status: 'System Status',
      active: 'Active',
      cloud: 'Cloud',
      local: 'Local',
      maintenance: 'System Under Maintenance',
      maintenance_desc: 'We are currently carrying out scheduled maintenance to provide you with a faster and more stable service. We will be active again very soon!',
      admin_login: 'Admin Login',
      announcements: 'Admin Announcements',
      back: 'Go Back',
      required: 'Required field',
      success: 'Success',
      error: 'Error',
      warning: 'Warning',
      fast_secure: 'Fast & Secure',
    },
    navbar: {
      more: 'Information & Help',
      corporate: 'Corporate & Info',
      guest: 'Guest',
      welcome: 'Welcome,',
      settings: 'Profile & Settings',
      admin_panel: 'Admin Panel',
      support_messages: 'Support Messages',
      theme_settings: 'UI Theme',
      theme_midnight: 'Midnight Blue (Deep Black)',
      theme_slate: 'Charcoal Gray (Slate)',
    },
    uploader: {
      title: 'Fast & Secure Image Uploading',
      subtitle: 'Upload your images instantly and share them with optimized links.',
      drag_drop: 'Drag and drop your images here or',
      browse: 'Browse Files',
      allowed_formats: 'PNG, JPG, JPEG, WEBP, GIF (Max. {size}MB)',
      uploading: 'Uploading Images...',
      success: 'Upload Successful!',
      guest_limit: 'You have {limit} guest uploads left. Sign up for unlimited storage and advanced features!',
      guest_exhausted: 'Your guest upload limit has been reached! Create a free account to continue uploading.',
      terms_warning: 'By uploading images, you agree to our terms of use.',
      private_mode: 'Private Image (Only visible to me)',
      auto_delete: 'Auto Delete Time',
      no_delete: 'Never Delete',
      delete_1h: 'Delete in 1 Hour',
      delete_1d: 'Delete in 1 Day',
      delete_7d: 'Delete in 7 Days',
      delete_30d: 'Delete in 30 Days',
      upload_btn: 'Upload Selected',
      clear_btn: 'Clear',
      upload_more: 'Upload More',
      viewer_link: 'Viewer Link',
      direct_link: 'Direct Image Link',
      html_link: 'HTML Code',
      bbcode_link: 'BBCode',
      select_all: 'Select All',
      editor: 'Editor',
      edit_image: 'Edit Image',
    },
    gallery: {
      title: 'My Personal Gallery',
      subtitle: 'Manage all your uploaded images from one place.',
      empty: 'You have not uploaded any images yet.',
      empty_desc: 'Go back to the home page to upload your first image!',
      delete_confirm: 'Are you sure you want to delete this image? This action cannot be undone.',
      private: 'Private',
      public: 'Public',
      views: 'views',
      total_images: 'Total Images',
      total_views: 'Total Views',
    },
    image_detail: {
      title: 'Image Details',
      uploaded_by: 'Uploaded By',
      uploaded_at: 'Upload Date',
      views: 'View Count',
      dimensions: 'Resolution',
      file_size: 'File Size',
      file_format: 'Format',
      expires_at: 'Deletion Date',
      links: 'Share Links',
      download: 'Download Image',
      report: 'Report Image',
      delete: 'Delete Image',
      delete_confirm: 'This image will be permanently deleted. Are you sure?',
      reported_success: 'Image has been successfully reported. Thank you.',
      copied_msg: 'Link copied successfully!',
    },
    premium: {
      title: 'Premium Plan',
      subtitle: 'Elevate your experience with unlimited speed, zero ads, and extra features.',
      features_title: 'Why Premium?',
      feat_ads: 'Ad-Free Experience',
      feat_ads_desc: 'No ads anywhere on the site.',
      feat_limit: 'Up to 25 Bulk Uploads',
      feat_limit_desc: 'Upload up to 25 images simultaneously in one go.',
      feat_speed: 'Unlimited Upload & Download Speed',
      feat_speed_desc: 'Maximum speed without bandwidth limitations.',
      feat_expiry: 'Permanent Images',
      feat_expiry_desc: 'Premium images are stored for a lifetime until you delete them.',
      feat_editor: 'Advanced Image Editor',
      feat_editor_desc: 'Crop, apply filters, and edit your images easily.',
      feat_support: '24/7 Priority Support',
      feat_support_desc: 'Your support tickets are resolved in less than 1 hour.',
      monthly: 'Monthly Plan',
      yearly: 'Yearly Plan',
      purchase: 'Purchase Premium',
      active_premium: 'Your Premium is Active',
      expires_at: 'Expiry Date: {date}',
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('lang') as Language) || 'tr';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('lang', newLang);
  };

  const t = (key: string, section: string = 'common'): string => {
    return translations[lang]?.[section]?.[key] || translations['tr']?.[section]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
